language: csharp
solution: Taviloglu.Wrike.ApiClient.sln
mono: none
dotnet:  2.0.0
script:
 - dotnet restore
before_install:
 - sudo apt-get install nunit-console
after_script:
 - dotnet test ./Taviloglu.Wrike.ApiClient.Tests.Unit/bin/Release/netcoreapp2.0/Taviloglu.Wrike.ApiClient.Tests.Unit.dll
 - dotnet test ./Taviloglu.Wrike.ApiClient.Core.Tests.Unit/bin/Release/netcoreapp2.0/Taviloglu.Wrike.ApiClient.Core.Tests.Unit.dll
 - dotnet test ./Taviloglu.Wrike.ApiClient.Tests.Integration/bin/Release/netcoreapp2.0/Taviloglu.Wrike.ApiClient.Tests.Integration.dll
