language: csharp
solution: Taviloglu.Wrike.ApiClient.sln
mono: none
dotnet: 1.1.5
script:
 - dotnet restore
before_install:
 - sudo apt-get install nunit-console
after_script:
 - nunit-console ./Taviloglu.Wrike.ApiClient.Tests.Unit/bin/Release/netcoreapp2.0/Taviloglu.Wrike.ApiClient.Tests.Unit.dll
 - nunit-console ./Taviloglu.Wrike.ApiClient.Core.Tests.Unit/bin/Release/netcoreapp2.0/Taviloglu.Wrike.ApiClient.Core.Tests.Unit.dll
 - nunit-console ./Taviloglu.Wrike.ApiClient.Tests.Integration/bin/Release/netcoreapp2.0/Taviloglu.Wrike.ApiClient.Tests.Integration.dll
