language: csharp
solution: Taviloglu.Wrike.ApiClient.sln
mono: none
dotnet:  2.1.15
script:
 - dotnet restore
before_install:
 - sudo apt-get install nunit-console
after_script:
 - dotnet test ./Taviloglu.Wrike.ApiClient.Tests.Unit/Taviloglu.Wrike.ApiClient.Tests.Unit.csproj
 - dotnet test ./Taviloglu.Wrike.Core.Tests.Unit/Taviloglu.Wrike.Core.Tests.Unit.csproj
 - dotnet test ./Taviloglu.Wrike.ApiClient.Tests.Integration/Taviloglu.Wrike.ApiClient.Tests.Integration.csproj
